config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "home#index"
  get "/about" => "home#about"

  resources :projects do
    resources :tasks # , only: [:show, :edit, :create, :destroy, :update]  #this is a nested resource. 
    resources :discussions  # , only: [:show, :edit, :create, :destroy, :update]
    resources :favourites, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

 resources :users, only: [:show]  # for showing the users favourites

end

app/models/task.rb
class Task < ActiveRecord::Base
  #checks for the combined uniqueness of the title AND the foreign key.
  validates :title, presence: {message: " - You have to provide a task. "}, uniqueness: {scope: :project_id} 

  belongs_to :project
  belongs_to :user

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def new
  end

  def create
    # render text: params  # this is great to see what info is in the form

    # we're going to make a new task and save it to the db. 
    # we need to assemble some info to make a new task. 
    # All the info came from the params, but is provided by two methods.
    @task = Task.new task_title_params
    @task.user = current_user
    find_project  # gets the project id for this task, puts it in @project
    @task.project = @project # puts in the project
    # @task.user = current_user # put more info in
    
    # debugger

    if @task.save
      redirect_to @project, notice: "Task created successfully! "
      # redirect_to @project is the same as:  redirect_to project_path(@project) 
    else
      # need to send the user back to show page, but we need to specify 
      # it's from the projects folder, don't look in the tasks folder.
      # @project and @task are declared above, these take the info
      # back to the show page
      @tasks = @project.tasks
      render "projects/show"
    end
  end

  # def show
  #   # render text: stopped!
  #   # @project.do_something
  # end

  def edit

    # render text: params[:project]  # this is great to see what info is in the form
    find_project
    @task_to_edit = Task.find params[:id]
    # @task_to_edit.project = params[:project]
    # render text: @task_to_edit.id

  end

  def destroy
    # render text: params  # this is great to see what info is in the form
    find_project
    task_to_die = current_user.tasks.find params[:id]
    task_to_die.destroy
    redirect_to project_path(@project), notice: "Task deleted successfully!! "
  end

  def update
    @task = Task.find params[:id]    
    # Need If else statement to sniff out which update tasks are 
    # to toggle the done/undone, and which are to add a new task

    if task_toggle_params[:done].to_s == "" 
      # updating the task text
      @task.update task_title_params
    else
      # toggling the done/undone status
      task_owner = User.find(@task.user_id)  
      @task.update task_toggle_params
      # render text: task_params[:done] + @task.user.id.to_s + " " + task_owner.id.to_s + " " + params[:id]
      # if someone other than the task owner completes the task, 
      # send email to task owner
      if current_user!= task_owner
        @task.user = current_user
        AnswersMailer.notify_task_owner(@task).deliver_later
      end
    end
    find_project
    redirect_to project_path(@project), notice: "Task updated successfully!! "
  end

  private

  def task_title_params
  params.require(:task).permit(:title)
  end

  def task_toggle_params
  params.require(:task).permit(:done) 
  end

  def find_project
    @project = Project.find params[:project_id] # creates an object filled with data
    redirect_to root_path, alert: "Access Denied" if current_user.blank?
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_tasks.html.erb
<%= task.title %>
        <span class="btn-group btn-group-xs" role="group" >
          <%# Rails sugar: You don't have to put the .id in below. %>
          <%# We're using the delete because we need an HTTP verb. %>
          <%# this link requires two parameters becuase the routes table shows /thing/:thing_id/thang/:id(.:format)  %>
          <%# note the colons in this, these are parameters required. %>
          <%= link_to "Edit", edit_project_task_path(@project, task) , class: "btn btn-info"  %>  <%# works %>
          <%= link_to "Delete", project_task_path(@project, task), method: :delete, 
          data: {confirm: "are you sure??"}, class: "btn btn-danger"  %>
        </span>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>So you wnat to edit your task huh?</h1>

<p>Project : <%=  @project.title %></p>
<p>Description: <%=  @project.description %></p>
<hr>

<%= form_for (@task_to_edit), url: ("/projects/" + @project.id.to_s + "/tasks/" + (@task_to_edit.id).to_s) , method: :patch  do |f| %>  <%# This line works, but is longer  %>
<%# note the variables @project and  @task below, by convention Rails will go to /questions/id/answers %>
<%# form_for [@project, @task] do |f| %>  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, value: @task_to_edit.title %>
  </div>
    <%= f.submit class: "btn btn-primary" %>
<% end %>
<hr>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>