config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "home#index"
  get "/about" => "home#about"

  resources :projects do
    resources :tasks # , only: [:show, :edit, :create, :destroy, :update]  #this is a nested resource. 
    resources :discussions  # , only: [:show, :edit, :create, :destroy, :update]
    resources :favourites, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

 resources :users, only: [:show]  # for showing the users favourites

end

app/models/project.rb
class Project < ActiveRecord::Base
  # validates :title, presence: {message: "Provide a title please. "}, uniqueness: true
  validates :title, presence: true, uniqueness: true
  # this last bit nullifies the question_id of all associated answers.
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, through: :discussions
  belongs_to :user

  has_many :users, through: :members
  has_many :members, dependent: :destroy

  has_many :tagifications, dependent: :destroy
  has_many :tags, through: :tagifications

  has_many :favourites, dependent: :destroy
  has_many :favourited_by_users, through: :favourites, source: :user

  # def banana
  #   puts "hello from project!"
  #   puts "my id is: #{self.id}"
  # end

  # def do_something
  #   puts "do_something"
  #   render text: "stopped!"
  # end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]
  
  def index
    # if the search term exists
    if params[:search_term]
      # grab_params  # REDUNDENT
      search_term = "\%" + @search_term + "\%"
      # send an instance variable with the project data that matches the search, order it by :id
      @projects = Project.all.where("title ILIKE ? OR description LIKE ?", search_term, search_term).order(:id)  
    else
      # send an instance variable with all project data
      @projects = Project.order(:id)  
    end
  end

  def new
    # send an instance variable of a new (and empty) Project object
    @project = Project.new
  end


  def create 

    # recieve the users inputs as params in a form
    # grab_params  # REDUNDENT
    # puts these params into an object called @project
    @project = Project.new grab_params
    @project.user = current_user
    if @project.save
      # flash[:notice]="Project saved! "
      redirect_to @project
    else
      # show the form again with error, and use the layout called "special". This will go to the new view in the questions folder. 
      # it's the same as  render "/questions/new"
      render :new  #, layout: "special"  
    end
  end

  def show
    # debugger
    # render text: params
    # send the project object to the show view
    find_project
    # send any existant associated tasks
    @tasks = @project.tasks  # array-like-thing ActiveRecord Relation
    # This is a new empty task object so that the user can add a task
    @task = Task.new
    @discussion = Discussion.new
    @discussions = @project.discussions # this is used to shorten things 
    # in the show.html.erb
    # @comments = @discussions.comments  # don't think this is possible
  end

  def edit
    # send a project object with the data that already exists
    find_project
  end

  def destroy
    find_project
      if @project.user == current_user && @project.destroy
        redirect_to projects_path, notice: "Project deleted successfully!! "
      else
        redirect_to projects_path, error: "Whoops, your project was not successfully deleted. "
      end
  end

  def update
    find_project
    if @project.update grab_params    #update returns t/f
      redirect_to @project
    else
      render :edit
    end
    # render text: params  #works, reveals all the params
  end

  private

  def grab_params
    grab_params = params.require(:project).permit(:title, :description, :due_date, user_ids: [], tag_ids: []) 
    # + params.require().permit(:commit, :search_term)
  end

  def find_project
    # with the id of from the URL, find the object
    @project = Project.find params[:id] 
    redirect_to root_path, alert: "Access Denied" if current_user.blank?
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%# Display any errors %>
<% if @project.errors.any? %>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%# An object called @project has been sent here, it is otherwise empty. %>

<%# form_for is a built-in view helper to generate a form.  %>
<%= simple_form_for @project, html: { class: 'form-horizontal' } do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :due_date %>
    <%= f.association :users, as: :check_boxes, label_method: :full_name %>
    <%= f.association :tags, as: :check_boxes, label_method: :tagname %>

  <%# you can add an option to the tag below "Click to submit" %>
  <%# But don't do it and Rails will put the correct label, either "Submit" or "Update" %>
  <%= f.submit class: "btn btn-primary" %>
<%# hitting send will by default send the form to whatever the name is, pluralise it, and put _path on the end. in this case "projects_path" %>



<% end %>

app/views/projects/edit.html.erb
<h1>Edit your project here</h1>
<%= render "form" %>

<%= link_to "delete", project_path(@project), method: :delete, data: {confirm: "Are you use you want to delete this project? "}, class: "btn btn-danger"   %>

app/views/projects/index.html.erb
<h1>HEre is a list of all the projects</h1>

<%# The variable projects has been sent by the projects_controller. It is an object that is full of all Projects objects.  %>
<% @projects.each do |p| %>
<h2> <%= link_to p.title, p %> </h2>
<%= p.description %>
<br>
<%= p.due_date %>

<%# I don't have to write p.id below, rails is clever. I think that if it is not given more info, when pressed it tries to find the 'show' action from the controller that sent us here.%>
<!-- <p><button> <%=  link_to "Edit this project", edit_project_path(p) %></button></p> --> <%# this works %>

<hr>
<% end %>

app/views/projects/new.html.erb
<h1>Make a new Project!</h1>

<%= render "form" %>

app/views/projects/show.html.erb
<h1><%= @project.title %> </h1>
<p><%= @project.description %> </p>
<%= link_to "Edit Project", edit_project_path(@project), class: "btn btn-info btn-sm btn-group" %>
<p>Due date: <%= @project.due_date %> </p>
<p>Members: <% @project.users.each do |user| %>
  &nbsp &nbsp <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
  <%= user.full_name %>   
<% end %>
<p>Tags: <% @project.tags.each do |tag| %>
  &nbsp &nbsp <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
  <%= tag.tagname %>    
<% end %>
<p class='grey'>Owned by: <%= @project.user.full_name %></p>
<p> 
<%# @project.user %>
<%# current_user %>
<% if current_user != @project.user %>    <%# the owner of the project can't favourite it. %>
  <% if user_signed_in? && current_user.favourited_this?(@project) %>
  <%# if user_signed_in?  %>
    <% @favourite = current_user.favourites.find_by_project_id(@project) %>
    <%= link_to "Unfavourite", project_favourite_path(@project, @favourite), method: :delete, class: "btn btn-info"  %>
  <% else %>
  <!-- check to see if there exists an object in the favourites join table that connects this user and this project. 
  to do this, look in the favourites table for this current_user and see if there is a project_id that matches this project. 
  to do this, send the current_user and the project_id to something that will check if there is an object that ties the tow together. 
  Better would be to send this current-suer to a function, get an array-like thing back, see if this project_id is in it.
  WHere should this function be? Well it's code that does stuff, so it should be in the model.
  Use this if/else statement to call a function called favourited_this? that will return t/f if it is in there. 
   <br>-->
  <%= link_to "Favourite", project_favourites_path(@project), method: :post, class: "btn btn-info"  %>

  <!-- Current user is <%# current_user.full_name %> <br>
  @project.id is <%# @project.id %> <br>
  current_user.favourited_this?(@project.id) is <%# current_user.favourited_this?(@project.id) %> <br>
  current_user.favourite_projects is <%# current_user.favourite_projects %> <br>
  Favourite.find 1 is <%# Favourite.find(1).id %> <br> -->
  <% end %>
<% end %>

</p>
<hr class='thick_line'>

<% if @task.errors.any? %>
  <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<h3>Tasks</h3>
<%# form_for(@task), url: project_tasks_path(@project) do |f| %>  <%# This line works, but is longer  %>
<%# note the variables @project and  @task below, by convention Rails will go to /projects/id/tasks/id %>

<%= form_for [@project, @task] do |f| %>  
  <%= f.submit class: 'btn btn-primary'%>
  <%= f.text_field :title, placeholder: "Add a new task here...", :autofocus=>true, class: "form-control" %>
<% end %>
<hr>

<div>Tasks to do
  <%# @tasks.each do |task|         this was replaced by the line below   %>
  <% @tasks.where(done: false).order(:created_at => :asc).each do |task|  %> 
    <div>
      <%= link_to "Undone", project_task_path(@project, task, task:{done: true}), method: :patch, class: "btn btn-info" %> 
      <%= render partial: "/tasks/tasks", locals: {task: task}  %>
    </div>
  <% end %>  
</div>
<br>
<div>Completed tasks
  <% @tasks.where(done: true).order(:created_at => :asc).each do |task|  %> 
    <div>
      <%= link_to "Done", project_task_path(@project, task, task:{done: false}), method: :patch, class: "btn btn-info" %>
      <%= render partial: "/tasks/tasks", locals: {task: task}  %>
    </div>
  <% end %>  
</div>
<hr class='thick_line'>


<h3>Discussions</h3>
<hr>
<% @project.discussions.each do |discussion_banana| %>
  <p class =' discussion_title'> <%= discussion_banana.title %></p>
  <p class=' discussion_desc'> <%= discussion_banana.description %> 
    <span class="btn-group btn-group-xs" role="group" >
      <%= link_to "Edit", edit_project_discussion_path(@project, discussion_banana) , class: "btn btn-info"  %>  <%# works %>
      <%= link_to "Delete", project_discussion_path(@project, discussion_banana), method: :delete, 
      data: {confirm: "are you sure??"}, class: "btn btn-danger"  %>
    </span>
  </p>
  <hr>
  <%# SHOW COMMENTS  %>
  <div class='comments'>
    <% discussion_banana.comments.each do |comment_banana| %>
      <p><%= comment_banana.body %>
        <span class="btn-group btn-group-xs" role="group" >
          <%= link_to "Edit", edit_discussion_comment_path(discussion_banana, comment_banana) , class: "btn btn-info"  %> 
          <%= link_to "Delete", discussion_comment_path(discussion_banana, comment_banana), method: :delete, 
          data: {confirm: "are you sure??"}, class: "btn btn-danger"  %>
        </span>
      </p>
    <% end %>

    <%# FORM FOR NEW COMMENTS %>
    <%= form_for [discussion_banana, @comment || Comment.new] do |f| %>
      <%= f.text_field :body, placeholder: "Enter comment here...", class: 'form-control' %>
      <%= f.submit "Create a comment", class: 'btn btn-primary'%>
    <% end %>

<%# byebug %>

  </div>
 <hr>
<br>
<% end %>
<%= form_for [@project, @discussion]  do |f| %>
  <%=  f.text_field :title, placeholder: "Enter discussion title here...", class: 'form-control' %>
  <%=  f.text_field :description, placeholder: "Enter discussion body here...", class: 'form-control' %>
  <%= f.submit class: 'btn btn-primary'%>
<% end %>