config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "home#index"
  get "/about" => "home#about"

  resources :projects do
    resources :tasks # , only: [:show, :edit, :create, :destroy, :update]  #this is a nested resource. 
    resources :discussions  # , only: [:show, :edit, :create, :destroy, :update]
    resources :favourites, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

 resources :users, only: [:show]  # for showing the users favourites

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: {message: "Comment title must be provided!!!"}

  belongs_to :discussion
  belongs_to :user

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  # checks for the presence of the title, note that these error messages are 
  # not shown with the flash messsages. Instead they become part of an array
  # of error messages that will be attached to instances of this class.
  validates :title, presence: {message: "A Discussiong title must be provided!!!"}
  validates :description, presence: {message: "A Discussiong title must be provided!!!"}

  # this last bit nullifies the question_id of all associated answers.
  has_many :comments, dependent: :destroy 

  belongs_to :project
  belongs_to :user

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :project_id, uniqueness: {scope: :user_id}
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  # validates :title, presence: {message: "Provide a title please. "}, uniqueness: true
  validates :title, presence: true, uniqueness: true
  # this last bit nullifies the question_id of all associated answers.
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, through: :discussions
  belongs_to :user

  has_many :users, through: :members
  has_many :members, dependent: :destroy

  has_many :tagifications, dependent: :destroy
  has_many :tags, through: :tagifications

  has_many :favourites, dependent: :destroy
  has_many :favourited_by_users, through: :favourites, source: :user

  # def banana
  #   puts "hello from project!"
  #   puts "my id is: #{self.id}"
  # end

  # def do_something
  #   puts "do_something"
  #   render text: "stopped!"
  # end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tagifications, dependent: :destroy
  has_many :projects, through: :tagifications

  validates :name, presence: true, uniqueness: true

end

app/models/tagification.rb
class Tagification < ActiveRecord::Base
  belongs_to :tag
  belongs_to :project
end

app/models/task.rb
class Task < ActiveRecord::Base
  #checks for the combined uniqueness of the title AND the foreign key.
  validates :title, presence: {message: " - You have to provide a task. "}, uniqueness: {scope: :project_id} 

  belongs_to :project
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :tasks
  has_many :discussions
  has_many :comments

  has_many :projects, through: :members
  has_many :members, dependent: :destroy

  has_many :favourites, dependent: :destroy
  has_many :favourite_projects, through: :favourites, source: :project

  # returns T/F if the user has favourited this 
  def favourited_this?(project_banana)
    # Favourite.where(user_id: this.id, project_id: project_banana.id).present?
    favourite_projects.include? project_banana
  end

  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}".squeeze.strip
    else
      email
    end
  end

  def find_favourites
    # finds all the favourites for this user, this only return that weird
    # array like thing. then i use the map method, which takes each 
    # element in the array like thing, and finds the project_id, and then
    # with this number it goes to the Project and finds each project object,
    # and then it shows the title of each projct object.
    favourites.map{ |ff|  Project.find(ff.project_id).title  }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render layout: "index_layout"
  end
  
  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def new
  end

  def create
    # render text: params  # this is great to see what info is in the form

    # we're going to make a new task and save it to the db. 
    # we need to assemble some info to make a new task. 
    # All the info came from the params, but is provided by two methods.
    @task = Task.new task_title_params
    @task.user = current_user
    find_project  # gets the project id for this task, puts it in @project
    @task.project = @project # puts in the project
    # @task.user = current_user # put more info in
    
    # debugger

    if @task.save
      redirect_to @project, notice: "Task created successfully! "
      # redirect_to @project is the same as:  redirect_to project_path(@project) 
    else
      # need to send the user back to show page, but we need to specify 
      # it's from the projects folder, don't look in the tasks folder.
      # @project and @task are declared above, these take the info
      # back to the show page
      @tasks = @project.tasks
      render "projects/show"
    end
  end

  # def show
  #   # render text: stopped!
  #   # @project.do_something
  # end

  def edit

    # render text: params[:project]  # this is great to see what info is in the form
    find_project
    @task_to_edit = Task.find params[:id]
    # @task_to_edit.project = params[:project]
    # render text: @task_to_edit.id

  end

  def destroy
    # render text: params  # this is great to see what info is in the form
    find_project
    task_to_die = current_user.tasks.find params[:id]
    task_to_die.destroy
    redirect_to project_path(@project), notice: "Task deleted successfully!! "
  end

  def update
    @task = Task.find params[:id]    
    # Need If else statement to sniff out which update tasks are 
    # to toggle the done/undone, and which are to add a new task

    if task_toggle_params[:done].to_s == "" 
      # updating the task text
      @task.update task_title_params
    else
      # toggling the done/undone status
      task_owner = User.find(@task.user_id)  
      @task.update task_toggle_params
      # render text: task_params[:done] + @task.user.id.to_s + " " + task_owner.id.to_s + " " + params[:id]
      # if someone other than the task owner completes the task, 
      # send email to task owner
      if current_user!= task_owner
        @task.user = current_user
        AnswersMailer.notify_task_owner(@task).deliver_later
      end
    end
    find_project
    redirect_to project_path(@project), notice: "Task updated successfully!! "
  end

  private

  def task_title_params
  params.require(:task).permit(:title)
  end

  def task_toggle_params
  params.require(:task).permit(:done) 
  end

  def find_project
    @project = Project.find params[:project_id] # creates an object filled with data
    redirect_to root_path, alert: "Access Denied" if current_user.blank?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @favourites = current_user.favourites
    # render text: @favourites
    @ffavourites = current_user.find_favourites
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navtabs.html.erb
<nav class=" navbar-default">
  <div class="row"> 
    <ul class="nav navbar-nav ">
      <li role="presentation" class="active"><a href="/">Home</a></li>
      <li role="presentation"><a href="/about">About</a></li>
      <li role="presentation"><%= link_to "All projects", projects_path %></li>
      <li role="presentation"><%= link_to "New project", new_project_path %></li>
      
        <% if user_signed_in? %>

          <li role="presentation">  Hello <%= current_user.first_name%></li>
          <li role="presentation">  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
          <li role="presentation">  <%= link_to "My Favourites", user_path(current_user) %> </li>
        <% else %>
          <li role="presentation"> <%= link_to "Sign In", new_user_session_path %> </li>
        <% end %>
      
    </ul>

   <span class="navbar-form navbar-right " role="search">
    <%= form_tag( projects_path, method: "get") do %>
      <div class="form-group">
        <%= label_tag(:search_term, "") %>
        <%= text_field_tag :search_term, nil, placeholder: 'Enter search term...' %>
      </div>
        <%= submit_tag "Search", class: "btn btn-default"  %>
    <% end %>
    </span> 

<!-- 
 <span class="pull-right">
      <%= form_tag projects_path, :method => 'post' do %>
      <%= text_field_tag :search_term %>
      <%= submit_tag "Search", class: "btn btn-default" %>
      <% end %>
    </span> -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PM Tool</title>
  <!-- The word "application" below goes to the manifest at stylesheets/application.css -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container">
    
    <%= render "layouts/navtabs" %>

    <%= flash[:notice] || flash[:alert] %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/index_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PM Tool</title>
  <%= stylesheet_link_tag    'external', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    
    <%= render "layouts/navtabs" %>

    <%= yield %>
  </div>
</body>
</html>